# Generated by Django 5.2.8 on 2025-11-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload cover image (overrides cover_image URL)', null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL to cover image'),
        ),
    ]
